version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: flunk-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flunk
      POSTGRES_PASSWORD: flunkpassword
      POSTGRES_DB: flunk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
